[package]
name = "bqvalid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.19.3"
tree-sitter-sql-bigquery = "0.0.6"
tree-sitter-traversal = "0.1.2"
clap = { version = "3.2.6", features = ["derive"] }